# This workflow will install snakemake and test rule bfq_all

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apt update && apt-get install -y gcc libyaml-dev
        python -m pip install --upgrade pip
        python -m pip install snakemake pyyaml==5.3.1 
        python --version
    - name: Test
      env:
        GCF_DB: ./src/gcfdb
      working-directory: ./.tests
      run: |
        snakemake -n -p -j1 bfq_all
